import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import Main from 'components/Main'
import Sobre from 'components/Sobre'
import Skills from 'components/Skills'
import Projetos from 'components/Projetos'
import Contato from 'components/Contato'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Samuel Tedeschi Developer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main/>

      <Sobre/>

      <Skills/>

      <Projetos/>

      <Contato/>
    </>
  )
}
